# Memoria que o Gradle pode usar para compilar.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8


# Usa as bibliotecas AndroidX (padrao atual do Android).
android.useAndroidX=true

# Estilo de codigo oficial do Kotlin.
kotlin.code.style=official

# Cada modulo tem sua propria classe R (padrao do template).
android.nonTransitiveRClass=true
